name: CI
on:
    workflow_call:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main
jobs:
    test:
        permissions:
            contents: read
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: oven-sh/setup-bun@v1
              with:
                  bun-version: latest
            - name: Build and test coverage
              run: |
                  bun install
                  bun add c8
                  bun run coverage
            - name: Coveralls
              uses: coverallsapp/github-action@master
              with:
                  github-token: ${{ secrets.GITHUB_TOKEN }}
