name: CI
on:
    workflow_call:
    pull_request:
        branches:
            - main
jobs:
    test:
        permissions:
            contents: read
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v5.0.0
              with:
                  persist-credentials: false
            - uses: actions/setup-node@v5.0.0
              with:
                  node-version-file: ".node-version"
            - name: Build and test
              run: |
                  npm ci
                  npm run test
