# based on esbuild release script (MIT licensed):
# https://github.com/evanw/esbuild/blob/master/.github/workflows/release.yml

name: Release
on:
    push:
        tags:
            - "v*"
jobs:
    release:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v2
              with:
                  node-version: "14.x"
                  cache: npm
            - name: Build and test
              run: |
                  npm ci
                  npm test
            - name: Extract changelog
              run: |
                  VERSION="${GITHUB_REF_NAME#v}"
                  CHANGELOG="$(awk -v ver="$VERSION" '/^## / { if (p) { exit }; if ($2 == ver) { p=1; next} } p' CHANGELOG.md)"
                  echo "CHANGELOG<<EOF" >> $GITHUB_ENV
                  echo "$CHANGELOG" >> $GITHUB_ENV
                  echo "EOF" >> $GITHUB_ENV
            - name: Create GitHub Release
              uses: softprops/action-gh-release@v1
              with:
                  body: ${{ env.CHANGELOG }}
                  prerelease: true
                  files: |
                    ./dist/bare
