name: Release
on:
    push:
        tags:
            - "v*"
jobs:
    test:
        uses: ./.github/workflows/ci.yml
    release:
        needs: test
        permissions:
            contents: write
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: oven-sh/setup-bun@v1
              with:
                  bun-version: latest
            - name: Build
              run: |
                  bun install
                  bun run build
            # based on esbuild release script (MIT licensed):
            # https://github.com/evanw/esbuild/blob/master/.github/workflows/release.yml
            - name: Extract changelog
              run: |
                  VERSION="${GITHUB_REF_NAME#v}"
                  CHANGELOG="$(awk -v ver="$VERSION" '/^## / { if (p) { exit }; if ($2 == ver) { p=1; next} } p' CHANGELOG.md)"
                  echo "CHANGELOG<<EOF" >> $GITHUB_ENV
                  echo "$CHANGELOG" >> $GITHUB_ENV
                  echo "EOF" >> $GITHUB_ENV
            - name: Create GitHub Release
              uses: softprops/action-gh-release@v1
              with:
                  body: ${{ env.CHANGELOG }}
                  prerelease: true
                  files: |
                    ./dist/bare
